In [63]:
import numpy as np
import math

def Choleskydecomp(A):
    L = np.copy(A)
    n = len(A)
    L[0][0] = math.sqrt(L[0,0]) 
    for j in range(n):
        L[j][j] = L[j][j]
        for k in range(j):
            L[j][j] -= (L[j][k])**2
        L[j][j] = math.sqrt(L[j][j])
        for i in range(j+1,n):
            L[i][j] = L[i][j]
            for k in range(j):
                L[i][j] -= L[i][k]*L[j][k]
            L[i][j] /= L[j][j]
    for i in range(n-1):
        for j in range(i+1,n):
            L[i][j] = 0.0
    return L

A = np.matrix([[1.0,1.0,1.0,1.0],[1.0,4.0,4.0,4.0],[1.0,4.0,9.0,9.0],[1.0,4.0,9.0,18.0]])
L = Choleskydecomp(A)
print(L)
print(L.dot(np.transpose(L)))
b = [0,1,2,3]

[[ 1.          0.          0.          0.        ]
 [ 1.          1.73205081  0.          0.        ]
 [ 1.          1.73205081  2.23606798  0.        ]
 [ 1.          1.73205081  2.23606798  3.        ]]
[[  1.   1.   1.   1.]
 [  1.   4.   4.   4.]
 [  1.   4.   9.   9.]
 [  1.   4.   9.  18.]]


In [64]:
print(A)

[[  1.   1.   1.   1.]
 [  1.   4.   4.   4.]
 [  1.   4.   9.   9.]
 [  1.   4.   9.  18.]]


In [91]:
def LLforwardsub (L,b):
    n = len(L)
    y = np.zeros(n)
    y[0] = b[0]
    for i in range(1, n):
        y[i] = b[i]
        for j in range(i):
            y[i] -= L[i][j]*y[j]
        y[i] /= L[i][i]
    return y

In [92]:
def LLbackwardsub (L,y):
    Lt = np.transpose(L)
    n = len(L)
    x = np.zeros(n)
    x[n-1] = y[n-1]/Lt[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] = x[i] - Lt[i][j]*x[j]
        x[i] /= Lt[i][i]
    return x

In [93]:
def LLsolve(LL,b):
    y = LLforwardsub(LL,b)
    x = LLbackwardsub(LL,y)
    return x

In [94]:
y = LLforwardsub(L, b)
y

array([ 0.        ,  0.57735027,  0.4472136 ,  0.33333333])

In [95]:
x = LLbackwardsub(L, y)
x

array([-0.33333333,  0.13333333,  0.08888889,  0.11111111])

In [96]:
LLsolve(L, b)

array([-0.33333333,  0.13333333,  0.08888889,  0.11111111])

In [97]:
np.dot(A, x)

matrix([[ 0.,  1.,  2.,  3.]])