## INF1608 - Análise Numérica - 2017.1
## Departamento de Informática - PUC-Rio 
## Prof. Hélio Lopes - lopes@inf.puc-rio.br
## http://www.inf.puc-rio.br/~lopes


## Lista 5

1) Implemente o método de Reflexão de Householder para a obtenção da decomposição QR de uma matriz quadrada nxn.
       
2) Implemente o método de Rotação de Givens para a obtenção da decomposição QR de uma matriz quadrada nxn.
     
3) Teste muito bem todos esses algoritmos!

In [75]:
import numpy as np
import math
from IPython.display import Image

In [76]:
def householder(A):
    R = np.copy(A)
    n = len(A)
    U = np.zeros(n*n).reshape((n,n))
    for i in range(n):
        x = R[i:n,i]
        e = np.zeros(len(x))
        e[0] = 1
        u = np.sign(x[0])*np.linalg.norm(x)*e + x
        u = u/np.linalg.norm(u)
        u = np.matrix(u)
        ut = np.transpose(u)
        R[i:n,i:n] = R[i:n,i:n] -2*np.dot( np.dot(ut, u) , R[i:n,i:n])
        U[i:n, i] = u
    return U, R

In [74]:
#A = np.matrix([[16.,2.,3.,13.],[5.,11.,10.,8.],[9.,7.,6.,12.],[4.,14.,15.,1.]])
A = np.matrix([[12., -51., 4.],[6.,167., -68.],[-4., 24., -41.]])
Q,R = householder(A)
print A
print Q
print R

[[  12.  -51.    4.]
 [   6.  167.  -68.]
 [  -4.   24.  -41.]]
[[ 0.96362411  0.          0.        ]
 [ 0.22237479  0.99846035  0.        ]
 [-0.14824986  0.05547002 -1.        ]]
[[ -1.40000000e+01  -2.10000000e+01   1.40000000e+01]
 [  8.88178420e-16  -1.75000000e+02   7.00000000e+01]
 [ -4.44089210e-16   0.00000000e+00   3.50000000e+01]]


In [62]:
def givensRotation(a, b):
    if b == 0:
        c = 1
        s = 0
    else:
        if abs(b) > abs(a):
            r = a/b
            s = 1/ math.sqrt(1 + (r**2))
            c = s*r
        else:
            r = b/a
            c = 1/ math.sqrt(1 + (r**2))
            s = c*r
    return c, s

def QRgivens(A):
    n = len(A)
    Q = np.eye(n)
    R = np.copy(A)
    for j in range(n-1):
        k = 0
        for i in range(n-1, j, -1):
            G = np.eye(n)
            c, s = givensRotation(R[i-1,j],R[i,j])
            G[i-1:i+1, i-1: i+1] = np.vstack((np.transpose(np.vstack((c,-s))), np.transpose(np.vstack((s, c)))))
            R = np.dot(np.transpose(G), R)
            Q = np.dot(Q,G)
    return Q, R

In [63]:
A = np.matrix([[12., -51., 4.],[6.,167., -68.],[-4., 24., -41.]])
Q,R = QRgivens(A)
print 'A, Q, R'
print A
print Q
print R
np.dot(Q,R)

A, Q, R
[[  12.  -51.    4.]
 [   6.  167.  -68.]
 [  -4.   24.  -41.]]
[[ 0.85714286 -0.39428571  0.33142857]
 [ 0.42857143  0.90285714 -0.03428571]
 [-0.28571429  0.17142857  0.94285714]]
[[  1.40000000e+01   2.10000000e+01  -1.40000000e+01]
 [  0.00000000e+00   1.75000000e+02  -7.00000000e+01]
 [  0.00000000e+00   1.95202322e-15  -3.50000000e+01]]


array([[  12.,  -51.,    4.],
       [   6.,  167.,  -68.],
       [  -4.,   24.,  -41.]])