## INF1608 - Análise Numérica - 2017.1
## Departamento de Informática - PUC-Rio 
## Prof. Hélio Lopes - lopes@inf.puc-rio.br
## http://www.inf.puc-rio.br/~lopes


# Exercícios resolvidos

R1) Faça uma função que verique se uma matriz A de tamanho nxn é estritamente diagonal dominante:
        Definição: Uma matriz A (nxn) é estritamente diagonal dominante se para toda linha i vale:
                   $$|A_{i,i}| > \sum_{i=1, i\ne j}^n |A_{i,j}|$$
                   
R2) Implemente o método de Jacobi para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o. 
        https://pt.wikipedia.org/wiki/M%C3%A9todo_de_Jacobi

R3) Implemente o método de Gauss-Seidel para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o.
        https://pt.wikipedia.org/wiki/M%C3%A9todo_de_Gauss-Seidel

## Lista 4

1) Implemente o método de Gradiente Conjugado para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o.
        https://en.wikipedia.org/wiki/Conjugate_gradient_method

2) Teste muito bem todos esses algoritmos!

## Solução

R1) Faça uma função que verique se uma matriz A de tamanho nxn é estritamente diagonal dominante: 

Definição: Uma matriz A (nxn) é estritamente diagonal dominante se para toda linha i vale:
  $$|A_{i,i}| > \sum_{i=1, i\ne j}^n |A_{i,j}|$$
 


In [118]:
import numpy as np
import math

def isdiagonaldominat(A):
    n = len(A)
    for i in range(n):
        soma = 0.0
        for j in range(n):
            if (i != j):
                a = A[i,j]
                soma += math.fabs(a)
        if (math.fabs(A[i,i]) <= soma):
            return False
    return True

A = np.matrix([[-2.0,1.0,0.0],[1.0,-2.0,1.0],[0.0,1.0,-2.0]])
print(A)
print(isdiagonaldominat(A))


[[-2.  1.  0.]
 [ 1. -2.  1.]
 [ 0.  1. -2.]]
False


R2) Implemente o método de Jacobi para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o. https://pt.wikipedia.org/wiki/M%C3%A9todo_de_Jacobi

In [119]:
import numpy as np

def jacobi(A,b,x0,N,TOL):

    nlin = len(A); #num. de linhas
    x = np.zeros(nlin); #cria x
   
    #iteracoes
    k = 1;
    while (k <= N):
        #iteracao de Jacobi
        for i in range(nlin):
            x[i] = 0.0;
            for j in range(i):
                x[i] = x[i] - A[i,j]*x0[j]
            for j in range(i+1,nlin):
                x[i] = x[i] - A[i,j]*x0[j]
            x[i] = (x[i] + b[i])/A[i,i]
        #criterio de parada
        if (np.linalg.norm(x-x0) < TOL):
            return x,k
        #prepara nova iteracao
        k = k+1;
        x0 = np.copy(x)
    return x0,k


A = np.matrix([[2.0,1.0],[5.0,7.0]])
b = np.array([11.0,13.0])
guess = np.array([1.0,1.0])

sol,n = jacobi(A,b,guess,100,0.000001)

print "A:"
print(A)

print "b:"
print(b)

print "x:"
print(sol)

print "||Ax-b||:"
print(np.linalg.norm(A.dot(sol)-b))

print "Numero de iteracoes:"
print(n)


A:
[[ 2.  1.]
 [ 5.  7.]]
b:
[ 11.  13.]
x:
[ 7.1111107  -3.22222137]
||Ax-b||:
3.92347242466e-06
Numero de iteracoes:
31


R3) Implemente o método de Gauss-Seidel para a solução de um sistema de equações lineares. Defina um critério de parada para o seu método, e explique-o. https://pt.wikipedia.org/wiki/M%C3%A9todo_de_Gauss-Seidel

In [120]:
import numpy as np

def gaussseidel(A,b,x0,N,TOL):

    nlin = len(A); #num. de linhas
    x = np.zeros(nlin); #cria x
   
    #iteracoes
    k = 1;
    while (k <= N):
        #iteracao de Jacobi
        for i in range(nlin):
            s = 0.0;
            for j in range(i):
                s = s + A[i,j]*x[j]
            for j in range(i+1,nlin):
                s = s + A[i,j]*x0[j]
            x[i] = (b[i] - s)/A[i,i]
        #criterio de parada
        if (np.linalg.norm(x-x0) < TOL):
            return x,k
        #prepara nova iteracao
        k = k+1;
        x0 = np.copy(x)
    return x0,k


A = np.matrix([[2.0,1.0],[5.0,7.0]])
b = np.array([11.0,13.0])
guess = np.array([1.0,1.0])

sol,n = gaussseidel(A,b,guess,100,0.000001)

print "A:"
print(A)

print "b:"
print(b)

print "x:"
print(sol)

print "||Ax-b||:"
print(np.linalg.norm(A.dot(sol)-b))

print "Numero de iteracoes:"
print(n)


A:
[[ 2.  1.]
 [ 5.  7.]]
b:
[ 11.  13.]
x:
[ 7.1111107  -3.22222193]
||Ax-b||:
5.3245767262e-07
Numero de iteracoes:
16


In [121]:
A = np.matrix([[4.,1.0],[1.0,3.]])
b = np.matrix([[1],[2]])
x0 = np.matrix([[2],[1]])
e = np.matrix([[0.0001],[0.0001]])
loop = 10
x, k = GradienteConjugado(A, b, x0, e, loop)
print k
print np.dot(A, x)
print b

10
[[ 1.00000001]
 [ 2.        ]]
[[1]
 [2]]


In [124]:
def GradienteConjugado(A, b, x, e, loop):
    n = len(b)
    r = b - np.dot(A,x)
    p = np.copy(r)
    for k in range(loop):
        rTr = np.transpose(r).dot(r)
        pTAp = np.dot(np.transpose(p), np.dot(A, p))
        alpha = rTr[0,0]/pTAp[0,0]
        #print 'Alpha ',alpha
        #print 
        x = x + alpha*p
        #print 'X ',x
        #print
        rsnew = r - alpha*np.dot(A, p)
        #print 'Rsnew ', rsnew
        #print 
        if (b - np.dot(A, x)).all() < e.all():
            break
        beta = np.transpose(rsnew).dot(rsnew) / rTr
        #print 'Beta ',beta
        #print 
        p = rsnew + beta[0,0]*p 
        #print 'P ', p
        #print 
        r = rsnew
        p = np.copy(rsnew)
    return x, k+1

In [125]:
A = np.matrix([[4.,1.0],[1.0,3.]])
b = np.matrix([[1],[2]])
x0 = np.matrix([[2],[1]])
e = np.matrix([[0.0001],[0.0001]])
loop = 10
x, k = GradienteConjugado(A, b, x0, e, loop)
print k
print np.dot(A, x)
print b

10
[[ 1.00000001]
 [ 2.        ]]
[[1]
 [2]]
