In [30]:
import numpy as np
def LUdecomp(A):
    n = len(A)
    U = np.copy(A)
    L = np.eye(n)
    for j in range(n-1):
        for i in range(j+1,n):
            L[i][j] = U[i][j]/U[j][j] 
            for k in range(j+1,n):
                U[i][k] = U[i][k] - L[i][j]*U[j][k]
    return U,L

In [31]:
A = [[1,1,1],[2,3,5], [4,6,8]]
U, L = LUdecomp(A)
print L
print U

[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [ 4.  2.  1.]]
[[ 1  1  1]
 [ 2  1  3]
 [ 4  2 -2]]


In [68]:
def LUdecomp(A):
    LU=np.copy(A)
    n =len(A)
    sign = 1.0
    p = range(n)
    for j in range(n-1):
        maxi = j
        c = abs(LU[j][j])
        for i in range(j+1,n):
            c1 = abs(LU[i][j])
            if (c1 > c):
                c = c1
                maxi = i
        if (j != maxi):
            sign *= -1.0
            itmp = p[j]
            p[j] = p[maxi]
            p[maxi] = itmp
            for k in range(n):
                dtmp = LU[maxi][k]
                LU[maxi][k] = LU[j][k]
                LU[j][k] = dtmp
        for i in range(j+1,n):
            LU[i][j] = LU[i][j]/LU[j][j]
            for k in range(j+1,n):
                LU[i][k] = LU[i][k] - LU[i][j]*LU[j][k]
    return LU,p,sign

In [69]:
A = np.matrix([[2.0,1.0,1.0,0.0],[4.0,3.0,3.0,1.0],[8.0,7.0,9.0,5.0],[6.0,7.0,9.0,8.0]])
LU, p, s = LUdecompPivot(A)
print LU

[[ 8.          7.          9.          5.        ]
 [ 0.75        1.75        2.25        4.25      ]
 [ 0.5        -0.28571429 -0.85714286 -0.28571429]
 [ 0.25       -0.42857143  0.33333333  0.66666667]]


In [70]:
def LUgetL(LU):
    L  = np.copy(LU)
    n  = len(LU)
    for i in range(0,n):
        L[i,i] = 1.0
        for j in range(i+1,n):
            L[i][j] = 0.0
    return L
    
def LUgetU(LU):
    U  = np.copy(LU)
    n  = len(LU)
    for i in range(1,n):
        for j in range(0,i):
            U[i][j] = 0.0
    return U

In [71]:
L = LUgetL(LU)
U = LUgetU(LU)
#print L
#print U
print np.dot(L,U)
print
print A

[[ 8.  7.  9.  5.]
 [ 6.  7.  9.  8.]
 [ 4.  3.  3.  1.]
 [ 2.  1.  1.  0.]]

[[ 2.  1.  1.  0.]
 [ 4.  3.  3.  1.]
 [ 8.  7.  9.  5.]
 [ 6.  7.  9.  8.]]


In [ ]:
def LUforwardsub (L,b, p):
    n = len(L)
    y = np.zeros(n)
    y[0] = b[p[0]]
    for i in range(1,n):
        y[i] = b[p[i]]
        for j in range(i):
            y[i] = y[i] - L[i][j]*y[j]
    return y