In [3]:
import numpy as np

In [79]:
def pivotize(m):
    """Creates the pivoting matrix for m."""
    n = len(m)
    ID = [[float(i == j) for i in xrange(n)] for j in xrange(n)]
    for j in xrange(n):
        row = max(xrange(j, n), key=lambda i: abs(m[i][j]))
        if j != row:
            ID[j], ID[row] = ID[row], ID[j]
    return ID

In [80]:
def lu(A):
    """Decomposes a nxn matrix A by PA=LU and returns L, U and P."""
    n = len(A)
    L = [[0.0] * n for i in xrange(n)]
    U = [[0.0] * n for i in xrange(n)]
    P = pivotize(A)
    A2 = matrixMul(P, A)
    #A2 = A.copy()
    for j in xrange(n):
        L[j][j] = 1.0
        for i in xrange(j+1):
            s1 = sum(U[k][j] * L[i][k] for k in xrange(i))
            U[i][j] = A2[i][j] - s1
        for i in xrange(j, n):
            s2 = sum(U[k][j] * L[i][k] for k in xrange(j))
            L[i][j] = (A2[i][j] - s2) / U[j][j]
    return L, U

In [54]:
def dfLU(a, n):
    u = np.zeros(n*n).reshape((n,n))
    l = np.zeros(n*n).reshape((n,n))
    i = 0; j = 0; k = 0;
    i = 0; j = 0; k = 0;
    for i in range(n): 
        for j in range(n):
            if j < i:
                l[j][i] = 0
            else:
                l[j][i] = a[j][i]
                for k in range(i):
                    l[j][i] = l[j][i] - l[j][k] * u[k][i]
                    
        for j in range(n):
            if j < i:
                u[i][j] = 0
            if i == j:
                 u[i][j] = 1
            else:
                u[i][j] = a[i][j] / l[i][i]
                for k in range(i):
                    u[i][j] = u[i][j] - ((l[i][k] * u[k][j]) / l[i][i])

    return l, u

In [59]:
def luT(a, n):
    u = np.zeros(n*n).reshape((n,n))
    l = np.zeros(n*n).reshape((n,n))
    i = 0; j = 0; k = 0;
    for i in range(n): 
        for j in range(n):
            if j < i:
                l[j][i] = 0
            else:
                l[j][i] = a[j][i]
                for k in range(i):
                    l[j][i] = l[j][i] - l[j][k] * u[k][i]
                    
        for j in range(n):
            if j < i:
                u[i][j] = 0
            if i == j:
                 u[i][j] = 1
            else:
                u[i][j] = a[i][j] / l[i][i]
                for k in range(i):
                    u[i][j] = u[i][j] - ((l[i][k] * u[k][j]) / l[i][i])
    return l, u

In [ ]:
def luV(a, n):
    u = a.copy()
    l = a.copy()
    
    i = 0; j = 0; k = 0;
    for i in range(n): 
        for j in range(n):
            if j < i:
                l[j][i] = 0
            else:
                l[j][i] = a[j][i]
                for k in range(i):
                    l[j][i] = l[j][i] - l[j][k] * u[k][i]
                    
        for j in range(n):
            if j < i:
                u[i][j] = 0
            if i == j:
                 u[i][j] = 1
            else:
                u[i][j] = a[i][j] / l[i][i]
                for k in range(i):
                    u[i][j] = u[i][j] - ((l[i][k] * u[k][j]) / l[i][i])
    return l, u

In [81]:
A = np.array([ [7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6] ])
A

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])

In [82]:
L, U = lu(A)

NameError: global name 'matrixMul' is not defined

In [73]:
L = np.asarray(L).reshape((len(L),len(L)))
print L

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-1.  0.  1.  0.]
 [ 0. -1.  0.  1.]]


In [74]:
U = np.asarray(U).reshape((len(U),len(U)))
print U

[[ 7.  3. -1.  2.]
 [ 0.  8.  1. -4.]
 [ 0.  0.  3.  1.]
 [ 0.  0.  0.  2.]]


In [75]:
print L*U

[[ 7.  0. -0.  0.]
 [ 0.  8.  0. -0.]
 [-0.  0.  3.  0.]
 [ 0. -0.  0.  2.]]


In [49]:
def LU_PUC(a, n):
    #u = a.copy()
    #l = a.copy()
    u = np.zeros(n*n).reshape((n,n))
    l = np.zeros(n*n).reshape((n,n))
    k =  0
    while(k < n):
    #for(k=1;k<=n;k++)
        u[k][k]=1;
        i = k
        while(i < n):
        #for(i=k;i<=n;i++)
            soma=0;
            p = 1
            while(p < (k-1) ):
            #for(p=1;p<=k-1;p++)
                soma+=l[i][p]*u[p][k];
                p = p + 1
            l[i][k]=a[i][k]-soma
            i = i + 1
        
        j = k + 1
        while(j < n):
        #for(j=k+1;j<=n;j++)
            soma=0;
            p = 1
            while(p < (k - 1) ):
            #for(p=1;p<=k-1;p++)
                soma+=l[k][p]*u[p][j];
                p = p + 1
            u[k][j]=(a[k][j]-soma)/l[k][k];
            j = j + 1
        k = k + 1
    return l, u 

In [60]:
L, U = LU_PUC(A, len(A))

In [61]:
print L

[[ 7.  0.  0.  0.]
 [ 3.  8.  0.  0.]
 [-1.  1.  4.  0.]
 [ 2. -4. -1.  4.]]


In [62]:
print U

[[ 1.          0.42857143 -0.14285714  0.28571429]
 [ 0.          1.          0.125      -0.5       ]
 [ 0.          0.          1.         -0.25      ]
 [ 0.          0.          0.          1.        ]]


In [53]:
L*U

array([[ 7.,  0., -0.,  0.],
       [ 0.,  8.,  0., -0.],
       [-0.,  0.,  4., -0.],
       [ 0., -0., -0.,  4.]])

In [57]:
q,w = dfLU(A, len(A))

In [58]:
q*w

array([[7, 0, 0, 0],
       [0, 8, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2]])