In [6]:
import numpy as np

In [8]:
def lu(A):
    n = len(A)
    L = np.zeros(n*n).reshape((n,n))
    U = np.zeros(n*n).reshape((n,n))
    for j in xrange(n):
        L[j][j] = 1.0
        for i in xrange(j+1):
            s1 = sum(U[k][j] * L[i][k] for k in xrange(i))
            U[i][j] = A[i][j] - s1
        for i in xrange(j, n):
            s2 = sum(U[k][j] * L[i][k] for k in xrange(j))
            L[i][j] = (A[i][j] - s2) / U[j][j]
    return L, U
 

In [9]:
a = [[4, 9, 2], [3, 5, 7], [8, 1, 6]]
np.asarray(a).reshape((len(a),len(a)))

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [11]:
l, u = lu(a)

In [12]:
l*u

array([[  4.        ,   0.        ,   0.        ],
       [  0.        ,  -1.75      ,   0.        ],
       [  0.        ,   0.        , -51.42857143]])

In [13]:
np.dot(l,u)

array([[ 4.,  9.,  2.],
       [ 3.,  5.,  7.],
       [ 8.,  1.,  6.]])

In [14]:
def findX(l, b):
    #Foward
    n = len(b)
    x = np.zeros(n)
    for i in xrange(1, n):
        x[i] = b[i]
        for j in range(1, i - 1):
            x[i] = x[i] - l[i][j]*x[j]
        x[i] = x[i]/l[i][i]
    return x

In [16]:
def findY(u, b):
    #backward
    n = len(b)
    y = np.zeros(n)
    for i in range( ((-1)*n), -1, -1):
        y[i]= b[i]
        for j in range(i + 1, n):
            y[i] = y[i] - u[i][j]*y[j]
    y[i] = y[i]/u[i][i]
    return y