In [45]:
import numpy as np
import pandas as pd

In [46]:
def lu(a, l, u, n):
    i = 0; j = 0; k = 0;
    for i in range(n): 
        for j in range(n):
            if j < i:
                l[j][i] = 0
            else:
                l[j][i] = a[j][i]
                for k in range(i):
                    l[j][i] = l[j][i] - l[j][k] * u[k][i]
                    
        for j in range(n):
            if j < i:
                u[i][j] = 0
            if i == j:
                 u[i][j] = 1
            else:
                u[i][j] = a[i][j] / l[i][i]
                for k in range(i):
                    u[i][j] = u[i][j] - ((l[i][k] * u[k][j]) / l[i][i])


In [47]:
a = [[4, 9, 2], [3, 5, 7], [8, 1, 6]]
l = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
u = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
n = len(a[0][:])
lu(a, l, u, n)

In [48]:
print u, l

[[1, 2, 0], [0, 1, -7], [0, 0, 1]] [[4, 0, 0], [3, -1, 0], [8, -15, -99]]


In [49]:
U = np.asarray(u)
U

array([[ 1,  2,  0],
       [ 0,  1, -7],
       [ 0,  0,  1]])

In [50]:
DataU = pd.DataFrame(U.reshape((3,3)), index = range(n), columns = range(n))
DataU

0  1  2
0  1  2  0
1  0  1 -7
2  0  0  1

In [51]:
L = np.asarray(l)
L

array([[  4,   0,   0],
       [  3,  -1,   0],
       [  8, -15, -99]])

In [52]:
DataL = pd.DataFrame(L.reshape((3,3)), index = range(n), columns = range(n))
DataL

0   1   2
0  4   0   0
1  3  -1   0
2  8 -15 -99

In [53]:
DataA = pd.DataFrame(np.asarray(a).reshape((n,n)), index = range(n), columns = range(n))
DataA

0  1  2
0  4  9  2
1  3  5  7
2  8  1  6

In [56]:
DataA[0][1]
np.zeros(9)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [62]:
def dfLU(a, n):
    i = 0; j = 0; k = 0;
    #l = pd.DataFrame(np.ones(n*n).reshape((n,n)), index = range(n), columns = range(n))
    #u = pd.DataFrame(np.ones(n*n).reshape((n,n)), index = range(n), columns = range(n))
    l = a.copy()
    u = a.copy()
    i = 0; j = 0; k = 0;
    for i in range(n): 
        for j in range(n):
            if j < i:
                l[j][i] = 0
            else:
                l[j][i] = a[j][i]
                for k in range(i):
                    l[j][i] = l[j][i] - l[j][k] * u[k][i]
                    
        for j in range(n):
            if j < i:
                u[i][j] = 0
            if i == j:
                 u[i][j] = 1
            else:
                u[i][j] = a[i][j] / l[i][i]
                for k in range(i):
                    u[i][j] = u[i][j] - ((l[i][k] * u[k][j]) / l[i][i])

    return l, u
            

In [63]:
L, U = dfLU(DataA, n)
print L
print U

   0  1   2
0  4  9   2
1  0  5   7
2  0  0  23
   0  1  2
0  1  0  0
1  0  1  0
2  2 -3  1


In [67]:
lista = [[8, 1, 6],[3, 5, 7],[4, 9, 2]]
df = pd.DataFrame(np.asarray(lista).reshape((3,3)))
df

0  1  2
0  8  1  6
1  3  5  7
2  4  9  2

In [70]:
Tl, Tu = dfLU(df,3)
Tl

0  1  2
0  8  1  6
1  0  5  7
2  0  0 -5

In [71]:
Tu

0  1  2
0  1  0  0
1  0  1  0
2  0  1  1